### ISSUE TITLE
Bug Report On Prism Launcher

### ISSUE THREAD

**Issue by mzz2345gj** [coltonk9043/Aoba-Client#77]
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
This is the error message returned. I am on prism launcher, with fabric API 102.0 on 1.21 installed, and the 1.4.3 version of Aoba installed for 1.21, how do I  troubleshoot? @coltonk9043

**Comment by mzz2345gj** [comment]
Follow-up: only 1.4.1 works for me, any version older than that and Minecraft is stuck at the loading screen

**Comment by BatchDebug** [comment]
Please make sure you are on the right version supported by the Aoba Client. You can find all the versions of Aoba for Minecraft on https://www.aobaclient.com/download

**Comment by coltonk9043** [comment]
Unfortunately that error message does not tell me much about what went wrong. Is there any way you could send me the entire log file on our Discord?

**Comment by mzz2345gj** [comment]
Sure, I don't have my computer with me right now, I will send later, as for the comment by @BatchDebug, I did download it from the right source, however only 1.4.1 loads for me

**Comment by BatchDebug** [comment]
Hi,
i was Not talking about the source but about the Minecraft Version. If only 1.4.1 is Working for you IT means you are in the wrong Minecraft Version for Aoba. Try These steps:
- Create a New Instance
- Name your Instance
- Select 1.21.3 (Because that has less Bugs)
-  Create the Instance and drop in the Aoba Client Jar and Install FabricAPI
- OPTIONAL: Install ViaFabricPlus for cross-version-compatibility
- Done

**Comment by mzz2345gj** [comment]
Issue fixed, thanks!

**Comment by BatchDebug** [comment]
No problem :D
